# Generated by Django 4.1.2 on 2023-01-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('order-placed', 'order-placed'), ('dispached', 'dispached'), ('on-delivery', 'on-delivery'), ('cancelled', 'cancelled')], default='order-placed', max_length=200),
        ),
    ]
